[package]
name = "hex_impl"
version = "0.0.1"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]
edition = "2021"
license = "MIT"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1"
