[package]
name = "name_from_path"
version = "0.0.1"
authors = ["Sachin Cherian <sachinctl@protonmail.com>"]
edition = "2021"
license = "MIT"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "1"

convert_case = "0.5"
